# Generated by Django 6.0.1 on 2026-01-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('age', models.IntegerField(max_length=32)),
                ('email', models.EmailField(max_length=123)),
            ],
        ),
    ]
